version: '3'
services:
  # mysql:
  #   # image: mysql:5.7.42-debian
  #   image: mysql:8.0.34-debian
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=changeme
  #     - MYSQL_DATABASE=moodle
  #     - MYSQL_USER=moodle
  #     - MYSQL_PASSWORD=changeme
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  # moodle:
  #   build: ./
  #   # image: moodle:311
  #   image: moodle:402
  #   user: root
  #   volumes:
  #     - ./wwwroot:/var/www/html/
  #     # - ./moodle_data:/var/www/moodledata
  #     - AFSMount:/mnt/moodledata
  #   # depends_on:
  #   #   - mysql
  #   ports:
  #     - 80:80
  php:
    build: ./
    image: moodle:426
    volumes:
      - ./src:/var/www/html
      - ./moodle_data:/var/www/moodledata
    depends_on:
      - mysql
    ports:
      - 8100:80
  mysql:
    image: mysql:8.0.34-debian
    environment:
      - MYSQL_ROOT_PASSWORD=binus12345
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=binus12345
    volumes:
      - ./mysql_data:/var/lib/mysql